/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerPersonStudent;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static view.Principal.*;

import static view.RegistryStudent.*;

/**
 *
 * @author Juan1
 */
public class Registry extends javax.swing.JPanel {

    //
    RegistryStudent rs = new RegistryStudent();
    RegistryStudentG rsg = new RegistryStudentG();
    RegistryTeacher rt = new RegistryTeacher();
    //
    Dimension WH = Toolkit.getDefaultToolkit().getScreenSize();

    ControllerPersonStudent controller = new ControllerPersonStudent();

    /**
     * Creates new form RegistryStudent
     */
    public Registry() {
        initComponents();
        initItems();//inicia
        loadComboActivity();
        loadComboCareer();
    }

    void initItems() {//inicia objetos
        rs.setSize(WH);
        rs.setLocation(0, 0);
        Container.add(rs, BorderLayout.CENTER);
        Container.revalidate();
        //

        Color color = new Color(41, 48, 81);
        btnExit.setBackground(color.white);
        rdbStudent.setBackground(color);
        rdbTeacher.setBackground(color);
        rdbGroup.setBackground(color);
    }

    void StartInitItems() {//reinica a la pantalla de inicio
        setVisible(false);
        btnStudent.setVisible(true);
        lbLogo.setVisible(true);
        lbClockStart.setVisible(true);
    }

    void Selected() {
        if (rdbStudent.isSelected()) {
            rsg.setVisible(false);
            rt.setVisible(false);
            rs.setVisible(true);
            rs.setSize(WH);
            rs.setLocation(0, 0);
            Container.add(rs, BorderLayout.CENTER);
            Container.revalidate();
            txtMatricula.requestFocus();
        } else if (rdbTeacher.isSelected()) {
            rs.setVisible(false);
            rsg.setVisible(false);
            rt.setVisible(true);
            rt.setSize(WH);
            rt.setLocation(0, 0);
            Container.add(rt, BorderLayout.CENTER);
            Container.revalidate();
            rt.txtNoTeacher.requestFocus();
        } else if (rdbGroup.isSelected()) {
            rs.setVisible(false);
            rt.setVisible(false);
            rsg.setVisible(true);
            rsg.setSize(WH);
            rsg.setLocation(0, 0);
            Container.add(rsg, BorderLayout.CENTER);
            Container.revalidate();
            rsg.txtNameG.requestFocus();
        }
    }

    void loadComboActivity() {//cargar el combo actividad 
        ResultSet result = controller.loadComboActivity();//crea un objeto de controler 
        try {
            while (result.next()) {
                RegistryStudent.cbxActivity.addItem(result.getString("nombre"));
                RegistryTeacher.cbxActivity.addItem(result.getString("nombre"));
                RegistryStudentG.cbxActivity.addItem(result.getString("nombre"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
        }
    }//individual && grupo

    void loadComboCareer() {//cargar el combo Carrera Grupo
        ResultSet result = controller.loadComboCareer();//crea un objeto de controler 
        try {
            while (result.next()) {
                RegistryStudent.cbxCarrera.addItem(result.getString("nombre"));
                RegistryTeacher.cbxCarrera.addItem(result.getString("nombre"));
                RegistryStudentG.cbxCarrera.addItem(result.getString("nombre"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error " + ex.getMessage());
        }
    }//individual

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgCareer = new javax.swing.ButtonGroup();
        tbngTRegistro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        lbDate = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        rdbStudent = new javax.swing.JRadioButton();
        rdbTeacher = new javax.swing.JRadioButton();
        rdbGroup = new javax.swing.JRadioButton();
        lbLogomini = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1100, 600));

        jPanel1.setBackground(new java.awt.Color(41, 48, 81));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        btnExit.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(41, 48, 84));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/126572-64.png"))); // NOI18N
        btnExit.setText("Inicio");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lbDate.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lbDate.setForeground(new java.awt.Color(255, 255, 255));
        lbDate.setText("0000-00-00");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Fecha:");

        Container.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Container.setPreferredSize(new java.awt.Dimension(1050, 396));

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1046, Short.MAX_VALUE)
        );
        ContainerLayout.setVerticalGroup(
            ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Registro por:");

        tbngTRegistro.add(rdbStudent);
        rdbStudent.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rdbStudent.setForeground(new java.awt.Color(255, 255, 255));
        rdbStudent.setSelected(true);
        rdbStudent.setText("Alumno");
        rdbStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbStudentActionPerformed(evt);
            }
        });

        tbngTRegistro.add(rdbTeacher);
        rdbTeacher.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rdbTeacher.setForeground(new java.awt.Color(255, 255, 255));
        rdbTeacher.setText("Docente");
        rdbTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbTeacherActionPerformed(evt);
            }
        });

        tbngTRegistro.add(rdbGroup);
        rdbGroup.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        rdbGroup.setForeground(new java.awt.Color(255, 255, 255));
        rdbGroup.setText("Grupo");
        rdbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbGroupActionPerformed(evt);
            }
        });

        lbLogomini.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoUTTmini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbStudent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbTeacher)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdbGroup))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnExit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                                .addComponent(lbLogomini)))
                        .addGap(153, 153, 153)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(lbDate))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lbLogomini))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lbDate, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(rdbStudent)
                    .addComponent(rdbTeacher)
                    .addComponent(rdbGroup))
                .addGap(7, 7, 7)
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        StartInitItems();
    }//GEN-LAST:event_btnExitActionPerformed


    private void rdbTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbTeacherActionPerformed
        // TODO add your handling code here:
        Selected();
    }//GEN-LAST:event_rdbTeacherActionPerformed

    private void rdbStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbStudentActionPerformed
        // TODO add your handling code here:
        Selected();
    }//GEN-LAST:event_rdbStudentActionPerformed

    private void rdbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbGroupActionPerformed
        // TODO add your handling code here:
        Selected();
    }//GEN-LAST:event_rdbGroupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.ButtonGroup btgCareer;
    public static javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbLogomini;
    private javax.swing.JRadioButton rdbGroup;
    private javax.swing.JRadioButton rdbStudent;
    private javax.swing.JRadioButton rdbTeacher;
    private javax.swing.ButtonGroup tbngTRegistro;
    // End of variables declaration//GEN-END:variables
}
